backend:
  name: github # GitHub backend ব্যবহার করার জন্য
  repo:  PathpukurSchool # আপনার GitHub ইউজারনেম এবং রিপোজিটরি নাম
  branch: main # আপনার কন্টেন্ট যে ব্রাঞ্চে আছে (সাধারণত main বা master)

media_folder: "static/images/uploads" # আপলোড করা ছবি কোথায় সংরক্ষণ করা হবে (আপনার প্রজেক্ট অনুযায়ী পথ পরিবর্তন করুন)
public_folder: "/images/uploads" # ওয়েবসাইটে ছবির URL পাথ

collections:
  - name: "notices" # আপনার কালেকশনের একটি অনন্য নাম (UI তেও ব্যবহৃত হয়)
    label: "নোটিশ" # UI তে প্রদর্শিত নাম
    folder: "content/notices" # GitHub রিপোজিটরিতে যেখানে নোটিশ ফাইলগুলো আছে
    create: true # নতুন নোটিশ তৈরি করার অনুমতি দিন
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # ফাইলের নামকরণের ফরম্যাট
    fields: # প্রতিটি নোটিশের জন্য যে ফিল্ডগুলো থাকবে
      - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
      - {label: "শিরোনাম", name: "title", widget: "string", required: true}
      - {label: "বিষয়বস্তু", name: "body", widget: "markdown"} # Markdown এডিটরের জন্য
      - {label: "ছবি", name: "image", widget: "image", required: false}
      - {label: "গুরুত্বপূর্ণ নোটিশ?", name: "is_important", widget: "boolean", default: false}

  - name: "pages"
    label: "পেজ"
    files:
      - label: "আমাদের সম্পর্কে"
        name: "about"
        file: "content/pages/about.md" # 'আমাদের সম্পর্কে' পেজের ফাইলের পথ
        fields:
          - {label: "শিরোনাম", name: "title", widget: "string"}
          - {label: "বিষয়বস্তু", name: "body", widget: "markdown"}
      - label: "যোগাযোগ"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - {label: "শিরোনাম", name: "title", widget: "string"}
          - {label: "বিষয়বস্তু", name: "body", widget: "markdown"}
          - {label: "ইমেইল", name: "email", widget: "string"}
