backend:
  name: github
  repo: pathpukurschool.github.io/ # e.g., your_github_username/your_repo_name
  branch: main # আপনার GitHub Pages branch, সাধারণত 'main' বা 'master'

publish_mode: editorial_workflow # এটি আপনাকে ড্রাফ্ট সেভ করতে এবং পাবলিশ করার আগে রিভিউ করতে দেবে।

media_folder: "assets/uploads" # আপলোড করা ছবির জন্য ফোল্ডার
public_folder: "/assets/uploads" # ফ্রন্টএন্ডে অ্যাক্সেস করার জন্য পাবলিক পাথ

collections:
  - name: "notices" # CMS এ এই কালেকশনের নাম
    label: "নোটিশ" # CMS UI তে প্রদর্শিত নাম
    folder: "_data" # GitHub এ যেখানে ডেটা সেভ হবে
    create: true # নতুন এন্ট্রি তৈরির অনুমতি
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # ফাইলের নাম ফরম্যাট (ঐচ্ছিক)
    identifier_field: "title" # ডিফল্ট টাইটেল ফিল্ড
    extension: "json" # ডেটা JSON ফরম্যাটে সেভ হবে
    format: "json" # ডেটা ফরম্যাট JSON
    fields: # প্রতিটি নোটিশ এন্ট্রির জন্য ফিল্ডগুলো
      - {label: "তারিখ", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "বিষয়বস্তু (সংক্ষিপ্ত হেডিং)", name: "title", widget: "string", required: true}
      - {label: "বিজ্ঞপ্তি (বিস্তারিত বিবরণ)", name: "body", widget: "markdown"} # Markdown এডিটরের জন্য
      - {label: "বর্ডারের রঙ", name: "color", widget: "color", default: "#CC0000"} # কালার পিকার
      - {label: "লিঙ্ক", name: "link", widget: "string", required: false} # ফাইল বা URL লিঙ্ক
      # যদি ফাইল আপলোড করতে চান, তবে এটি যোগ করুন:
      # - {label: "PDF/File আপলোড", name: "file", widget: "file", required: false}
